// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NajlONline.Models;

namespace NajlONline.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20220706090821_naziv")]
    partial class naziv
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NajlONline.Models.AdresaModel", b =>
                {
                    b.Property<Guid>("AdresaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Broj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdresaID");

                    b.ToTable("Adrese");
                });

            modelBuilder.Entity("NajlONline.Models.KarticaModel", b =>
                {
                    b.Property<Guid>("KarticaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojRacuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CVC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatumIsteka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("KorisnikID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KarticaID");

                    b.HasIndex("KorisnikID");

                    b.ToTable("Kartice");
                });

            modelBuilder.Entity("NajlONline.Models.KategorijaModel", b =>
                {
                    b.Property<Guid>("KategorijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Godine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivKategorije")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategorijaID");

                    b.ToTable("Kategorije");
                });

            modelBuilder.Entity("NajlONline.Models.KorisnikModel", b =>
                {
                    b.Property<Guid>("KorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdresaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Lozinka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UlogaID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KorisnikID");

                    b.HasIndex("AdresaID");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique()
                        .HasFilter("[KorisnickoIme] IS NOT NULL");

                    b.HasIndex("UlogaID");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("NajlONline.Models.KupovinaModel", b =>
                {
                    b.Property<Guid>("KupovinaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumKupovine")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<Guid>("KorisnikID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ProizvodDostavljen")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProizvodID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ProizvodPorucen")
                        .HasColumnType("bit");

                    b.Property<bool>("UspesnaKupovina")
                        .HasColumnType("bit");

                    b.HasKey("KupovinaID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("ProizvodID");

                    b.ToTable("Kupovine");
                });

            modelBuilder.Entity("NajlONline.Models.ProizvodModel", b =>
                {
                    b.Property<Guid>("ProizvodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("KategorijaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KorisnikID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SezonaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrenutnoStanje")
                        .HasColumnType("int");

                    b.Property<string>("Velicina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VrstaProizvodaID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProizvodID");

                    b.HasIndex("KategorijaID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("SezonaID");

                    b.HasIndex("VrstaProizvodaID");

                    b.ToTable("Proizvodi");
                });

            modelBuilder.Entity("NajlONline.Models.SezonaModel", b =>
                {
                    b.Property<Guid>("SezonaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Godina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivSezone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SezonaID");

                    b.ToTable("Sezone");
                });

            modelBuilder.Entity("NajlONline.Models.UlogaModel", b =>
                {
                    b.Property<Guid>("UlogaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UlogaID");

                    b.ToTable("Uloge");
                });

            modelBuilder.Entity("NajlONline.Models.VrstaProizvodaModel", b =>
                {
                    b.Property<Guid>("VrstaProizvodaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivPodvrsteProizvoda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivVrsteProizvoda")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VrstaProizvodaID");

                    b.ToTable("VrsteProizvoda");
                });

            modelBuilder.Entity("NajlONline.Models.KarticaModel", b =>
                {
                    b.HasOne("NajlONline.Models.KorisnikModel", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("NajlONline.Models.KorisnikModel", b =>
                {
                    b.HasOne("NajlONline.Models.AdresaModel", "Adresa")
                        .WithMany()
                        .HasForeignKey("AdresaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NajlONline.Models.UlogaModel", "Uloga")
                        .WithMany()
                        .HasForeignKey("UlogaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adresa");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("NajlONline.Models.KupovinaModel", b =>
                {
                    b.HasOne("NajlONline.Models.KorisnikModel", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NajlONline.Models.ProizvodModel", "Proizvod")
                        .WithMany()
                        .HasForeignKey("ProizvodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("NajlONline.Models.ProizvodModel", b =>
                {
                    b.HasOne("NajlONline.Models.KategorijaModel", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NajlONline.Models.KorisnikModel", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NajlONline.Models.SezonaModel", "Sezona")
                        .WithMany()
                        .HasForeignKey("SezonaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NajlONline.Models.VrstaProizvodaModel", "VrstaProizvoda")
                        .WithMany()
                        .HasForeignKey("VrstaProizvodaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");

                    b.Navigation("Korisnik");

                    b.Navigation("Sezona");

                    b.Navigation("VrstaProizvoda");
                });
#pragma warning restore 612, 618
        }
    }
}
